version: "3"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    networks:
      - webnet
    volumes:
      - "./qdrant_storage:/qdrant/storage"

  search_server:
    build: .
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - qdrant

networks:
  webnet:
    driver: bridge
